export const GET_EVENTS = 'GET_EVENTS'
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS'
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE'

export const GET_USER = 'GET_EVENTS'
export const GET_USER_SUCCESS = 'GET_EVENTS_SUCCESS'
export const GET_USER_FAILURE = 'GET_EVENTS_FAILURE'

