const GET_PULLS = 'GET_PULLS';
const GET_FORKS = 'GET_FORKS';
const RECEIVED_PULLS = 'RECEIVED_PULLS';
const RECEIVED_FORKS = 'RECEIVED_FORKS'

const GET_EVENTS = 'GET_EVENTS'
const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';

